version: '3.9'
services:
  elastics01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elastics01
    environment:
      - node.name=elastics01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastics01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
####################################
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    depends_on:
      - "elastics01"
        #condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elastics01:9200
      ELASTICSEARCH_HOSTS: http://elastics01:9200
    ports:
    - 5601:5601
    networks:
    - elastic
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
